travis:
  secure:
    BINSTAR_TOKEN: Ctmkx5u6OJLEBIz8BOSHqsmC3SL8K3tiVTcfrqMb2CESZK1QPsJhMY1Ove3OskTztEC4hOCMsq11IsEOPX92rFtwH7TTPbaiFVMhWUI6Y129+pAUUfRpEjNIQRyjxrRpE2UeoNFI9CrUAyRQ6A7ooYGEXLJ+i+OW3LkdwF9DSiR/JJTxrtcwrmqSIoqtQaqzGAl4y0z8xB1/x5n1ykGngpx2mFS2D1qi3LS0USBhViaOfjEUxrUm9IEhBqL1mcjG/MDuT7fHquPjay22Aoy3uEf5WAkBpAY79BXM1Op9+FMi2tAX2Iv5704ll4jTx1TP+FHohpCbxZhfblgl/eR39CP4sS/KS0t0Qv+G+6RE0z+cuUeslS6zS+gWlNfZHePMV9/q+WDi3+Fwgh4cJXkum42ZxpUV8MU+42G/N3vYO/mQj5v/oB3QSx97KTpUpB/Hiug1iVDVRYPwminrG5QDgtljcdal9SA2/SEqyOPvtAHtAAXNMRbD1pT7TP616w/Xf7Ad5GnQJpf2ptPc7GsrkaN2vxDqo36xUlSDUr4rJ+H84k9wVq2O2jdXdHXgNZak4mYekDT8jCyM4WdmLXh5CBGczUVf4kOwxbGqW0TCHuYAmzXJI4LZSyowXe6I3cJHjsidngQ5izMjY8Otkxa83/mji+Hy239dr25DY4Tauwo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
